version: "3.9"

services:
  service:
    image: ecommerce-basket-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-basket-service
    ports:
      - 1003:8080
    environment:
      - JWT_SECRET=DockerTestJWTFakeSecret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - RABBITMQ_HOST=host.docker.internal
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - CATALOG_SERVICE_BASE_URL=http://host.docker.internal:1002
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: redis
    container_name: ecommerce-basket-service-redis
    ports:
      - 6379:6379
    restart: on-failure
